configs:
  repositories:
    argocd:
      name: argocd
      type: git
      url: https://github.com/ymatsiuk/argo.git
    bitnamicharts:
      name: bitnami
      type: helm
      url: registry-1.docker.io/bitnamicharts
      enableOCI: "true"
  clusterCredentials:
     dev:
        server: https://kubernetes.default.svc
        name: dev
        labels:
          environment: dev
        config: {}
dex:
  enabled: false
global:
  logging:
    level: debug
