{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    app.kubernetes.io/component: {{ .name }}
    kubernetes.io/metadata.name: {{ .name }}
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    linkerd.io/inject: {{ .linkerd | default "enabled" }}
    {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
    {{- end }}
{{- end }}
