apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: default
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/ymatsiuk/argo.git
            revision: HEAD
            files:
            - path: "applications/*/*/*/chart.yaml"
        - list:
            elements:
            - valueFiles:
              - "applications/{{ item.path.segments.1 }}/{{ item.path.segments.2 }}/values.yaml"
              - "applications/{{ item.path.segments.1 }}/{{ item.path.segments.2 }}/{{ item.path.segments.3 }}/values.yaml"
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                kubernetes.io/environment: '{{ index .path.segments 3 }}'
  template:
    metadata:
      name: '{{ index .path.segments 2 }}'
      namespace: HEAD
    spec:
      project: '{{ index .path.segments 1 }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .chart.namespace | default (index .path.segments 2) }}'
      source:
      - repoURL: '{{ .chart.repoURL }}'
        chart: '{{ .chart.name }}'
        targetRevision: '{{ .chart.version | toString }}'
        helm:
          releaseName: '{{ .chart.releasename | default (index .path.segments 2 | trunc 53) }}'
          ignoreMissingValueFiles: true
  templatePatch: |
    spec:
      source:
        helm:
          valueFiles:
          {{- range $valueFile := .valueFiles }}
            - {{ $valueFile }}
          {{- end }}
