apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: default
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
        - git:
            repoURL: https://github.com/ymatsiuk/argo.git
            revision: HEAD
            files:
            - path: "applications/*/*/*/chart.yaml"
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                kubernetes.io/environment: '{{ index .path.segments 3 }}'
  template:
    metadata:
      name: '{{ index .path.segments 2 }}'
      namespace: HEAD
    spec:
      project: '{{ index .path.segments 1 }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .chart.namespace | default (index .path.segments 2) }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply={{ .chart.serversideapply | default "true" }}
      sources:
      - repoURL: https://github.com/ymatsiuk/argo.git
        targetRevision: HEAD
        ref: src
      - repoURL: '{{ .chart.repoURL }}'
        chart: '{{ .chart.name }}'
        targetRevision: '{{ .chart.version | toString }}'
        {{- if .chart.path }}
        path: '{{ .chart.path }}'
        {{- end }}
        helm:
          releaseName: '{{ .chart.releasename | default (index .path.segments 2 | trunc 53) }}'
          ignoreMissingValueFiles: true
          valueFiles:
          - '$src/applications/{{ index .path.segments 1 }}/{{ index .path.segments 2 }}/values.yaml'
          - '$src/applications/{{ index .path.segments 1 }}/{{ index .path.segments 2 }}/{{ index .path.segments 3 }}/values.yaml'
      - repoURL: https://github.com/ymatsiuk/argo.git
        targetRevision: HEAD
        directory:
          recurse: true
        path: 'applications/{{ index .path.segments 1 }}/{{ index .path.segments 2 }}/{{ index .path.segments 3 }}'
